### ISSUE TITLE
Compilation failure with Enchant 2

### ISSUE THREAD

**Issue by Arfrever** [psi-im/libpsi#10]
Psi 1.2 fails to build with Enchant 2:
```
libpsi/tools/spellchecker/enchantchecker.cpp: In constructor ‘EnchantChecker::EnchantChecker()’:
libpsi/tools/spellchecker/enchantchecker.cpp:38:34: error: ‘instance’ is not a member of ‘enchant::Broker’
  if (enchant::Broker *instance = enchant::Broker::instance())
                                  ^~~~~~~
libpsi/tools/spellchecker/enchantchecker.cpp: In member function ‘virtual bool EnchantChecker::add(const QString&)’:
libpsi/tools/spellchecker/enchantchecker.cpp:83:23: error: ‘class enchant::Dict’ has no member named ‘add_to_pwl’
    spellers_.first()->add_to_pwl(word.toUtf8().constData());
                       ^~~~~~~~~~
libpsi/tools/spellchecker/enchantchecker.cpp: In member function ‘virtual void EnchantChecker::setActiveLanguages(const QList<QString>&)’:
libpsi/tools/spellchecker/enchantchecker.cpp:114:17: error: ‘instance’ is not a member of ‘enchant::Broker’
    spellers_ << enchant::Broker::instance()->request_dict(lang.toStdString());
                 ^~~~~~~
```

**Comment by Ri0n** [comment]
just fixed in master branch

**Comment by Arfrever** [comment]
Commits:
https://github.com/psi-im/libpsi/commit/98938fa30a7d6157e0382bd59928a006406858f3
https://github.com/psi-im/libpsi/commit/1aba347fc8ea8e6e58b5b7cee5203ad69963a856
https://github.com/psi-im/libpsi/commit/23277486f0ecdb16180c751b212784fe39dd8b55
https://github.com/psi-im/psi/commit/8367c528a4e8198cb1ac460c87cdafdd3d8fb813
https://github.com/psi-im/psi/commit/41fbc7f04524104947572462a6937cb7556b3213
https://github.com/psi-im/psi/commit/4f2147b422c594acd35d21cd88315db6d9e3be49

By the way, why a pointer added in the first commit is named `brocker` instead of `broker`?

**Comment by Ri0n** [comment]
because I don't have much time for sleep =)
I'll change it. thanks.

**Comment by Arfrever** [comment]
https://github.com/psi-im/libpsi/commit/9882f7256120391cb664c22245889028f360b55b
