### ISSUE TITLE
Minizip is forked from zlib into another project

### ISSUE THREAD

**Issue by rapgro** [psi-im/libpsi#13]
Development of minizip as part of zlib is dead. There should be an option to skip the bundled version.

Please port sources to use the new API provided in minizip version 2.8 series.
We fail to unbundle in Fedora and it's not possible to build with another dependency to the new package built from the minizip fork.
https://github.com/nmoinvaz/minizip

Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1632194

**Comment by Ri0n** [comment]
Let me understand you correctly
1. There is nothing wrong with minizip bundled in Psi. It works well.
2. Fedora migrates to a newer minizip version which Psi can't use for now. So only bundled version works.
3. And this request is about adding support of compilation against the only maintained minizip fork which haven't been added to any distro but Fedora.

**Comment by tehnick** [comment]
@rapgro 
Why did you opened this duplicating issue?

**Comment by tehnick** [comment]
https://github.com/psi-im/psi/issues/388

**Comment by tehnick** [comment]
@Ri0n 
I am going to disable `Issues` sections for `psi-im/libpsi` and `psi-im/iris` repos. Do you have objections?

https://github.com/psi-im/psi/issues is already pointed out as bug tracker in all documentation of Psi and Psi+ projects.

**Comment by tehnick** [comment]
As for `iris` repo I am not so sure. But for `libpsi` repo this should make sense.

**Comment by tehnick** [comment]
@rapgro 
See https://github.com/nmoinvaz/minizip/issues/358 as well.

**Comment by rapgro** [comment]
Yes. But the downstream maintainer wants to drop the compat subpackage in zlib. That means one option only to live with the bundle and consider it as a backfork.

**Comment by tehnick** [comment]
@rapgro Please read comments from links above and continue discussion there.

**Comment by rapgro** [comment]
Sorry, I'm obviously too lazy. Bare with me as a poor downstream packager.

**Comment by tehnick** [comment]
@rapgro No problem here. We all humans. =)

**Comment by Ri0n** [comment]
> As for iris repo I am not so sure. But for libpsi repo this should make sense.
I'm fine with disable for libpsi

**Comment by Neustradamus** [comment]
I think it is better to separate minizip.
